name: add version tag
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  create_git_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TAG: ${{github.event.pull_request.title}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
      - run: |
        echo "${{github.event.pull_request.title}}" > TAG_NAME
        git tag $(cat TAG_NAME)
        git push origin $(cat TAG_NAME)